# Generated by Django 3.0.4 on 2020-04-11 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1500)),
                ('question_author', models.CharField(max_length=100)),
                ('question_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_answer', models.TextField()),
                ('question_answer_author', models.CharField(default='Одинокий фотограф', max_length=100)),
                ('question_answer_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
