# Generated by Django 3.0.4 on 2020-04-11 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя отвечающего'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_author',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=1500, verbose_name='Вопрос'),
        ),
    ]
