# Generated by Django 3.0.4 on 2020-04-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_auto_20200411_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_answer_author',
        ),
    ]
