# Generated by Django 3.0.4 on 2020-04-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_remove_question_question_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_answer_author',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
    ]
