# Generated by Django 3.0.4 on 2020-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_question_question_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_answer_author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя отвечающего'),
        ),
    ]
