# Generated by Django 3.0.4 on 2020-04-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_auto_20200411_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
